### ISSUE TITLE
Multiple Patterns 

### ISSUE THREAD

**Issue by mthota15** [markfink/korg#8]
What is the efficient way to parse multiple patterns for given log line?

Here is what i am doing?

from korg import LineGrokker, PatternRepo
pr = PatternRepo()

patterns = [
    '%{HTTPD_COMBINEDLOG}',
    '%{HTTPD_COMMONLOG}',
    '%{HTTPD_ERRORLOG}'
]

def parse_type(ia):
    for k in range(len(patterns)):
        return LineGrokker(patterns[k], pr).grok(ia)

text = '::1 - - [26/Dec/2016:16:16:29 +0200] "GET /favicon.ico HTTP/1.1" 404 209'
print(parse_type(text))

**Comment by markfink** [comment]
you do not split up the pattern string like in your code but provice the pattern as a single string (similar to logstash). I provided a sample in the README.
